spring.datasource.url=jdbc:postgresql://ep-calm-bird-a87wkq99-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SgQdJ32WZFKk
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
server.error.include-message=always